### ISSUE TITLE
raspberry pi media server

### ISSUE THREAD

**Issue by mkeyno** [kisPocok/rpi3-plex-server#1]
sorry to open the ticket for my question , I actually look for media server which is run in Web/GUI browser  and client can easily browse media file that allow to brows , do you have any experience and suggestion?

**Comment by kisPocok** [comment]
Hi @mkeyno! Don't worry and sorry for the delay. I think it worth to try Plex! Alternatively use Kodi. Both of them have web based GUI.

Tell me more about your needs!

**Comment by mkeyno** [comment]
thanks buddy
